### ISSUE TITLE
I need you help! Hackintosh-OpenCore-EFI-for-MSI-GL65-Leopard-10SER-453IT

### ISSUE THREAD

**Issue by paoapaogege** [alessiocameroni/alessiocameroni#1]
Hi dude, I'm interested in your black Apple system.My computer is also MSI's gl65 leopard.But I'm just starting to figure out how to turn my computer into an Apple system.I saw the efi file on GitHub that you once shared, and I hope you can become friends with me and help me solve the problem of installing MAC OS on my laptop.Thank you so much and hope you can help me!

**Comment by paoapaogege** [comment]
Hi, brother. Why didn't you answer me? I have successfully installed the Mac OS Monterey 12.5 system. But my sound card and WiFi Bluetooth have no effect. I'm puzzled and don't know what to do. Finally, I decided to come to you. I hope you can help me find out what went wrong. Our laptop configuration is similar. I hope you can help me see if it is the EFI problem or the driver problem. Thank you very much. I hope we can have close contact. Thank you!

**Comment by alessiocameroni** [comment]
Hello. 
I haven't replied to you for different reasons:
- You opened an Issue instead of a Pull Request;
- You opened an Issue on a repository completely unrelated to what you are asking. This is not how Issues and Pull Requests work on GitHub..., you need help with my hackintosh EFI, then ask in the hackintosh EFI repo. Do some research before interacting with repos and/or people;
- You are asking for help, but you haven't provided any proper info I can work with so that I can help you fully;
- I am fairly busy;
- What you asked is something that could be useful to someone else trying to install Hackintosh on their device. If we talk about this privately, the process won't be publicly available, and consequentially it won't be documented online;

I will close and then tomorrow delete this issue as it does not pelong here.
